# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 11fqkk(番茄看看)

on:
  workflow_dispatch:
  schedule:
     - cron: '35 0,3,8,11 * * *'
  watch:
    types: started
#env:
  #TZ: Asia/Shanghai

jobs:
  build:
    env:
      fqkkurl: ${{ secrets.fqkkurl }}
      fqkkhd: ${{ secrets.fqkkhd }}
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      BARK_SOUND: ${{ secrets.BARK_SOUND }}
      DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
      DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}


    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/x101013416/123.git ~/123
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/123
          npm install -g npm
          npm update

      - name: '运行 【番茄看看】'
        if: env.fqkkurl
        run: |
          cd ~/123
          node Task/11fqkk.js
        env:
          fqkkurl: ${{ secrets.fqkkurl }}
          fqkkhd: ${{ secrets.fqkkhd }}
