# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# 运行时间从北京时间12点半开始，每隔90分钟一次，执行6次，最后一次在晚上8点
name: fqkk@feizao3 

on:
  workflow_dispatch:
  schedule:
     - cron: '0 6-12/3 * * *'
     - cron: '30 4-10/3 * * *'
  watch:
    types: started

jobs:
  build:
    env:  
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}


    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install -g npm
          npm update

      - name: '运行 【番茄看看】'
        if: env.fqkkurl
        run: |
          node Task/fqkk.js
        env:
          fqkkurl: ${{ secrets.fqkkurl }}
          fqkkhd: ${{ secrets.fqkkhd }}




